### ISSUE TITLE
Yahoo Finance Widget not in Time Series in Orange 3.30

### ISSUE THREAD

**Issue by mohad26** [biolab/orange3-timeseries#190] opened 2021-11-07 09:41 UTC
When I add in Time Series version 0.3.12  in Orange version 3.30 "last version" the Yahoo Finance widget is not included. How do I add in the Yahoo Finance widget?
##### Associate version

Orange version 3.30 "last version"
![orange](https://user-images.githubusercontent.com/81151427/140638256-a34d6a9b-5c39-4b72-b03c-9b00fa7e6315.jpg)

##### Expected behavior

include yahoo widget 

##### Actual behavior

Not include yahoo widget 

![orange](https://user-images.githubusercontent.com/81151427/140638322-9efbc3ca-9d8b-4ff7-a396-5acf58a85ee0.jpg)

**Comment by ajdapretnar** [comment] 2022-05-23 07:03
Duplicate of https://github.com/biolab/orange3-timeseries/issues/172.

**Closed by ajdapretnar** 2022-05-23 07:03 UTC
