### ISSUE TITLE
Install orange3-timeseries failed in Orange3-3.27.0.zip

### ISSUE THREAD

**Issue by yuanxin-cq** [biolab/orange3-timeseries#137] opened 2020-10-17 03:03 UTC
My os is windows10 ,chinese enviroment.
The error information as below:
It seems that 'gbk' code is the reason.
 
Collecting Orange3-Timeseries==0.3.7
  Using cached Orange3-Timeseries-0.3.7.tar.gz (1.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\SOFTWARE\Orange\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yuanxin\\AppData\\Local\\Temp\\pip-install-o3orlh5r\\orange3-timeseries\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yuanxin\\AppData\\Local\\Temp\\pip-install-o3orlh5r\\orange3-timeseries\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Yuanxin\AppData\Local\Temp\pip-pip-egg-info-3zj3ow0h'
         cwd: C:\Users\Yuanxin\AppData\Local\Temp\pip-install-o3orlh5r\orange3-timeseries\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Yuanxin\AppData\Local\Temp\pip-install-o3orlh5r\orange3-timeseries\setup.py", line 9, in <module>
        LONG_DESCRIPTION = open(README_FILE).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 834: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kernc** [comment] 2020-10-17 10:35
Duplicate of https://github.com/biolab/orange3-timeseries/issues/135.

**Closed** 2020-10-23 09:20 UTC
