### ISSUE TITLE
seasonal adjustment error

### ISSUE THREAD

**Issue by anamilkochar** [biolab/orange3-timeseries#82] opened 2020-03-26 05:14 UTC
![image](https://user-images.githubusercontent.com/62685742/77612625-a4214f00-6f4e-11ea-8a5e-8f8d7fa5c6c5.png)

please fix the same trying to run seasonal adjustment widget on a time series dataset

**Comment by ajdapretnar** [comment] 2020-03-26 11:10
Duplicate of #76.

**Closed by ajdapretnar** 2020-03-26 11:10 UTC
