### ISSUE TITLE
Time offset (1hr) in Line Chart

### ISSUE THREAD

**Issue by dekosan** [biolab/orange3-timeseries#180] opened 2021-12-01 16:37 UTC
**What's wrong?**

I'm producing a line chart using the following:
CSV File Import > Select Columns > As Timeseries
using the following csv format:
Time	Temp	Humid	Press	TCO2	TVOC
2021-11-29 17:43:23	21.29	45.87	1007.51	552	23

The graph is fine, but the graph starts at 18:43:23

It is not UTC because in this case it should be 16:43:23

**How can we reproduce the problem?** 

Load a file using parameters as above

**What's your environment?**

- Operating system: Mac OS 10.13.6 and 10.15.7
- Orange version: 3.30.2
- How you installed Orange: using dmg installer
[NewLog3.txt](https://github.com/biolab/orange3/files/7635626/NewLog3.txt)

**Comment by PrimozGodec** [comment] 2021-12-06 18:37
Transfering it to orange3-timeseries since the widget belongs to here.

**Comment by ajdapretnar** [comment] 2022-08-03 10:02
Partially fixed in #220.
Now the issue is that datetime with a single date and different hours gets rendered strangely. I'll close this issue and open another one.

**Closed by ajdapretnar** 2022-08-03 10:02 UTC
