### ISSUE TITLE
Error Widget - "Line Chart"

### ISSUE THREAD

**Issue by jeancarlotm** [biolab/orange3-timeseries#168] opened 2021-05-14 16:25 UTC
Error Widget - "Line Chart"

"Line Chart" Widget is not showing information on the chart, in one of the widgte.

attached the images of the possible bug.
![Orange](https://user-images.githubusercontent.com/80775698/118300682-97e0b400-b4b8-11eb-9700-b4c352bb5ea5.JPG)
![Orange_](https://user-images.githubusercontent.com/80775698/118300700-9c0cd180-b4b8-11eb-981a-0731f7fdcb14.JPG)

**Comment by PrimozGodec** [comment] 2021-05-14 16:59
Can you give me some more inforamtion. Did any additional window with an error appear when you connected data to the Line Chart?

FYI, today I implemented few fixes to the widget (https://github.com/biolab/orange3-timeseries/pull/167) maybe it will solve your issue.

**Comment by ajdapretnar** [comment] 2021-05-17 07:16
I would say a duplicate of #162 and possibly of #161.

**Comment by pepeto** [comment] 2021-07-28 12:30
@PrimozGodec Hi! How can I get the fix or the new owlinechart.py file? I am having the same problem. The window is empty. Thank you!

**Comment by PrimozGodec** [comment] 2021-09-23 09:17
@pepeto sorry for the late response. Now, orage3-timeseries is released. Just upgrade the addon from addons dialog

**Closed** 2022-05-22 18:44 UTC
